// Code generated by go generate; DO NOT EDIT

package cmds

import "testing"

func array0(s Builder) {
	s.Arcount().Key("1").Build()
	s.Ardel().Key("1").Index(1).Index(1).Build()
	s.Ardelrange().Key("1").Start(1).End(1).Start(1).End(1).Build()
	s.Arget().Key("1").Index(1).Build()
	s.Argetrange().Key("1").Start(1).End(1).Build()
	s.Argrep().Key("1").Start("1").End("1").Exact().String("1").And().Build()
	s.Argrep().Key("1").Start("1").End("1").Exact().String("1").Or().Build()
	s.Argrep().Key("1").Start("1").End("1").Exact().String("1").Limit(1).Build()
	s.Argrep().Key("1").Start("1").End("1").Exact().String("1").Withvalues().Build()
	s.Argrep().Key("1").Start("1").End("1").Exact().String("1").Nocase().Build()
	s.Argrep().Key("1").Start("1").End("1").Exact().String("1").Build()
	s.Argrep().Key("1").Start("1").End("1").Match().String("1").And().Build()
	s.Argrep().Key("1").Start("1").End("1").Match().String("1").Or().Build()
	s.Argrep().Key("1").Start("1").End("1").Match().String("1").Limit(1).Build()
	s.Argrep().Key("1").Start("1").End("1").Match().String("1").Withvalues().Build()
	s.Argrep().Key("1").Start("1").End("1").Match().String("1").Nocase().Build()
	s.Argrep().Key("1").Start("1").End("1").Match().String("1").Build()
	s.Argrep().Key("1").Start("1").End("1").Glob().Pattern("1").And().Build()
	s.Argrep().Key("1").Start("1").End("1").Glob().Pattern("1").Or().Build()
	s.Argrep().Key("1").Start("1").End("1").Glob().Pattern("1").Limit(1).Build()
	s.Argrep().Key("1").Start("1").End("1").Glob().Pattern("1").Withvalues().Build()
	s.Argrep().Key("1").Start("1").End("1").Glob().Pattern("1").Nocase().Build()
	s.Argrep().Key("1").Start("1").End("1").Glob().Pattern("1").Build()
	s.Argrep().Key("1").Start("1").End("1").Re().Pattern("1").And().Build()
	s.Argrep().Key("1").Start("1").End("1").Re().Pattern("1").Or().Build()
	s.Argrep().Key("1").Start("1").End("1").Re().Pattern("1").Limit(1).Build()
	s.Argrep().Key("1").Start("1").End("1").Re().Pattern("1").Withvalues().Build()
	s.Argrep().Key("1").Start("1").End("1").Re().Pattern("1").Nocase().Build()
	s.Argrep().Key("1").Start("1").End("1").Re().Pattern("1").Build()
	s.Arinfo().Key("1").Full().Build()
	s.Arinfo().Key("1").Build()
	s.Arinsert().Key("1").Value("1").Value("1").Build()
	s.Arlastitems().Key("1").Count(1).Rev().Build()
	s.Arlastitems().Key("1").Count(1).Build()
	s.Arlen().Key("1").Build()
	s.Armget().Key("1").Index(1).Index(1).Build()
	s.Armset().Key("1").Index(1).Value("1").Index(1).Value("1").Build()
	s.Arnext().Key("1").Build()
	s.Arop().Key("1").Start(1).End(1).Sum().Build()
	s.Arop().Key("1").Start(1).End(1).Min().Build()
	s.Arop().Key("1").Start(1).End(1).Max().Build()
	s.Arop().Key("1").Start(1).End(1).And().Build()
	s.Arop().Key("1").Start(1).End(1).Or().Build()
	s.Arop().Key("1").Start(1).End(1).Xor().Build()
	s.Arop().Key("1").Start(1).End(1).Match().Value("1").Build()
	s.Arop().Key("1").Start(1).End(1).Used().Build()
	s.Arring().Key("1").Size(1).Value("1").Value("1").Build()
	s.Arscan().Key("1").Start(1).End(1).Limit(1).Build()
	s.Arscan().Key("1").Start(1).End(1).Build()
	s.Arseek().Key("1").Index(1).Build()
	s.Arset().Key("1").Index(1).Value("1").Value("1").Build()
}

func TestCommand_InitSlot_array(t *testing.T) {
	var s = NewBuilder(InitSlot)
	t.Run("0", func(t *testing.T) { array0(s) })
}

func TestCommand_NoSlot_array(t *testing.T) {
	var s = NewBuilder(NoSlot)
	t.Run("0", func(t *testing.T) { array0(s) })
}
