// Code generated DO NOT EDIT

package cmds

import (
	"testing"
	"time"
)

func string0(s Builder) {
	s.Append().Key("1").Value("1").Build()
	s.Decr().Key("1").Build()
	s.Decrby().Key("1").Decrement(1).Build()
	s.Get().Key("1").Build()
	s.Get().Key("1").Cache()
	s.Getdel().Key("1").Build()
	s.Getex().Key("1").ExSeconds(time.Second).Build()
	s.Getex().Key("1").PxMilliseconds(time.Second).Build()
	s.Getex().Key("1").ExatTimestamp(time.Now()).Build()
	s.Getex().Key("1").PxatMillisecondsTimestamp(time.Now()).Build()
	s.Getex().Key("1").Persist().Build()
	s.Getex().Key("1").Build()
	s.Getrange().Key("1").Start(1).End(1).Build()
	s.Getrange().Key("1").Start(1).End(1).Cache()
	s.Getset().Key("1").Value("1").Build()
	s.Incr().Key("1").Build()
	s.Incrby().Key("1").Increment(1).Build()
	s.Incrbyfloat().Key("1").Increment(1).Build()
	s.Lcs().Key1("1").Key2("1").Len().Idx().Minmatchlen(1).Withmatchlen().Build()
	s.Lcs().Key1("1").Key2("1").Len().Idx().Minmatchlen(1).Build()
	s.Lcs().Key1("1").Key2("1").Len().Idx().Withmatchlen().Build()
	s.Lcs().Key1("1").Key2("1").Len().Idx().Build()
	s.Lcs().Key1("1").Key2("1").Len().Minmatchlen(1).Build()
	s.Lcs().Key1("1").Key2("1").Len().Withmatchlen().Build()
	s.Lcs().Key1("1").Key2("1").Len().Build()
	s.Lcs().Key1("1").Key2("1").Idx().Build()
	s.Lcs().Key1("1").Key2("1").Minmatchlen(1).Build()
	s.Lcs().Key1("1").Key2("1").Withmatchlen().Build()
	s.Lcs().Key1("1").Key2("1").Build()
	s.Mget().Key("1").Key("1").Build()
	s.Mget().Key("1").Key("1").Cache()
	s.Mset().KeyValue().KeyValue("1", "1").KeyValue("1", "1").Build()
	s.Msetnx().KeyValue().KeyValue("1", "1").KeyValue("1", "1").Build()
	s.Psetex().Key("1").Milliseconds(1).Value("1").Build()
	s.Set().Key("1").Value("1").Nx().Get().ExSeconds(time.Second).Build()
	s.Set().Key("1").Value("1").Nx().Get().PxMilliseconds(time.Second).Build()
	s.Set().Key("1").Value("1").Nx().Get().ExatTimestamp(time.Now()).Build()
	s.Set().Key("1").Value("1").Nx().Get().PxatMillisecondsTimestamp(time.Now()).Build()
	s.Set().Key("1").Value("1").Nx().Get().Keepttl().Build()
	s.Set().Key("1").Value("1").Nx().Get().Build()
	s.Set().Key("1").Value("1").Nx().ExSeconds(time.Second).Build()
	s.Set().Key("1").Value("1").Nx().PxMilliseconds(time.Second).Build()
	s.Set().Key("1").Value("1").Nx().ExatTimestamp(time.Now()).Build()
	s.Set().Key("1").Value("1").Nx().PxatMillisecondsTimestamp(time.Now()).Build()
	s.Set().Key("1").Value("1").Nx().Keepttl().Build()
	s.Set().Key("1").Value("1").Nx().Build()
	s.Set().Key("1").Value("1").Xx().Get().Build()
	s.Set().Key("1").Value("1").Xx().ExSeconds(time.Second).Build()
	s.Set().Key("1").Value("1").Xx().PxMilliseconds(time.Second).Build()
	s.Set().Key("1").Value("1").Xx().ExatTimestamp(time.Now()).Build()
	s.Set().Key("1").Value("1").Xx().PxatMillisecondsTimestamp(time.Now()).Build()
	s.Set().Key("1").Value("1").Xx().Keepttl().Build()
	s.Set().Key("1").Value("1").Xx().Build()
	s.Set().Key("1").Value("1").Get().Build()
	s.Set().Key("1").Value("1").ExSeconds(time.Second).Build()
	s.Set().Key("1").Value("1").PxMilliseconds(time.Second).Build()
	s.Set().Key("1").Value("1").ExatTimestamp(time.Now()).Build()
	s.Set().Key("1").Value("1").PxatMillisecondsTimestamp(time.Now()).Build()
	s.Set().Key("1").Value("1").Keepttl().Build()
	s.Set().Key("1").Value("1").Build()
	s.Setex().Key("1").Seconds(1).Value("1").Build()
	s.Setnx().Key("1").Value("1").Build()
	s.Setrange().Key("1").Offset(1).Value("1").Build()
	s.Strlen().Key("1").Build()
	s.Strlen().Key("1").Cache()
}

func TestCommand_InitSlot_string(t *testing.T) {
	var s = NewBuilder(InitSlot)
	t.Run("0", func(t *testing.T) { string0(s) })
}

func TestCommand_NoSlot_string(t *testing.T) {
	var s = NewBuilder(NoSlot)
	t.Run("0", func(t *testing.T) { string0(s) })
}
