// Code generated by go generate; DO NOT EDIT

package cmds

import "testing"

func graph0(s Builder) {
	s.GraphConfigGet().Name("1").Build()
	s.GraphConfigSet().Name("1").Value("1").Build()
	s.GraphConstraintCreate().Key("1").Mandatory().Node("1").Properties(1).Prop("1").Prop("1").Build()
	s.GraphConstraintCreate().Key("1").Mandatory().Relationship("1").Properties(1).Prop("1").Prop("1").Build()
	s.GraphConstraintCreate().Key("1").Unique().Node("1").Properties(1).Prop("1").Prop("1").Build()
	s.GraphConstraintCreate().Key("1").Unique().Relationship("1").Properties(1).Prop("1").Prop("1").Build()
	s.GraphConstraintDrop().Key("1").Mandatory().Node("1").Properties(1).Prop("1").Prop("1").Build()
	s.GraphConstraintDrop().Key("1").Mandatory().Relationship("1").Properties(1).Prop("1").Prop("1").Build()
	s.GraphConstraintDrop().Key("1").Unique().Node("1").Properties(1).Prop("1").Prop("1").Build()
	s.GraphConstraintDrop().Key("1").Unique().Relationship("1").Properties(1).Prop("1").Prop("1").Build()
	s.GraphDelete().Graph("1").Build()
	s.GraphExplain().Graph("1").Query("1").Build()
	s.GraphList().Build()
	s.GraphProfile().Graph("1").Query("1").Timeout(1).Build()
	s.GraphProfile().Graph("1").Query("1").Build()
	s.GraphQuery().Graph("1").Query("1").Timeout(1).Build()
	s.GraphQuery().Graph("1").Query("1").Build()
	s.GraphRoQuery().Graph("1").Query("1").Timeout(1).Build()
	s.GraphRoQuery().Graph("1").Query("1").Timeout(1).Cache()
	s.GraphRoQuery().Graph("1").Query("1").Build()
	s.GraphRoQuery().Graph("1").Query("1").Cache()
	s.GraphSlowlog().Graph("1").Build()
}

func TestCommand_InitSlot_graph(t *testing.T) {
	var s = NewBuilder(InitSlot)
	t.Run("0", func(t *testing.T) { graph0(s) })
}

func TestCommand_NoSlot_graph(t *testing.T) {
	var s = NewBuilder(NoSlot)
	t.Run("0", func(t *testing.T) { graph0(s) })
}
