version: 2.1
orbs:
  go: circleci/go@1.7.3
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    parallelism: 4
    steps:
      - checkout
      - go/install:
          version: 1.20.4
      - run:
          command: ./dockertest.sh $(go list ./... | circleci tests split --split-by=timings)
          no_output_timeout: 30m
